### ISSUE TITLE
Enhance aankondigingen with toggleable mentions

### ISSUE THREAD

**Issue by th8** [RMTweedeKamer/Griffier#10]
1. Have users be able to assign themselves to a `Reminders` role.
2. Let aankondigingen mention that role when posting an announcement.

**Comment by Streepje** [comment]
Reminders role seems nice but not everyone wants to be reminded of the same notifications.

**Comment by th8** [comment]
TK and EK members now mentioned on voting threads. Other notifications can be enabled within Discord itself and do not require a bot solution.
