### ISSUE TITLE
Wait until flair is given before posting to #media

### ISSUE THREAD

**Issue by th8** [RMTweedeKamer/Griffier#36]
I think it'd be a good idea to make the announcer wait for the user to assign a reddit flair to their post in /r/RMTKMedia, before posting a link in the media announcement channel.

This not only encourages users to appropriately flair their posts aiding in searching for posts, it also helps display the proper flairs in front of the title in discord as it usually posts a link before one can feasibly apply a flair to ones post.

**Comment by ghost** [comment]
This has been solved in commit https://github.com/RMTweedeKamer/Griffier/pull/35/commits/8a2bea0d7d5dcda2a8e8dc048cabc5f7b0bdbadf
